name: IRis CI Workflow

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Build
        run: |
          cd src
          dotnet build

      - name: Run tests with coverage
        run: |
          cd ../tests
          dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/TestResults/
