name: PR Create
on:
  pull_request_target:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const author = "ShahzaibAhmad05";

            const pr = context.payload.pull_request;
            const contributor = pr.user.login;
            const body = pr.body || "";

            await github.rest.reactions.createForIssue({
              ...context.repo,
              issue_number: pr.number,
              content: "eyes"
            });

            if (contributor === author)
              return;

            await github.rest.pulls.requestReviewers({
              ...context.repo,
              pull_number: pr.number,
              reviewers: [author]
            });

            const matches = body.match(/#(\d+)/g);

            if (matches == null) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr.number,
                body: `@${contributor} Thank you for the pull request. Please also mention what issue this pr resolves.`
              });
            }

            else if (matches.length >= 1) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr.number,
                body: `@${contributor} tysm for the pull request! The maintainer has been notified and will review it soon.`
              });
            }
            